"""Deploy Penumbra (API + console) to Azure Container Apps.

    uv run python scripts/deploy_azure.py [--resource-group penumbra-rg] [--location centralindia]

What it creates, in the resource group the Sentinel deployment already uses:

  an Azure Container Registry, with both images built locally (Docker) and pushed to it
  a Container Apps environment (no log shipping: the app has its own audit chain and /metrics)
  penumbra-api      internal ingress only: reachable from the console, not from the internet
  penumbra-console  public HTTPS; proxies /api to penumbra-api inside the environment

Public-deployment rules, enforced here rather than remembered:

  * no demo users - PENUMBRA_ALLOW_DEMO_USERS is never set
  * analyst / senior / admin get generated 24-character passwords, stored as Container Apps secrets
    and written ONLY to artifacts/deploy/credentials.env (gitignored); never printed
  * a read-only guest (PENUMBRA_GUEST_ACCESS) so judges need no password
  * a generated JWT secret and PII key, so tokens survive restarts and pseudonyms are not the
    public development key (the API refuses to start on that)
  * the demo fixtures seed an empty store on start, so a restart comes back with the same data

Re-running rebuilds the images and updates the apps in place; existing secrets are reused.
Requires `az login`.
"""

from __future__ import annotations

import argparse
import json
import secrets
import shutil
import string
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CREDENTIALS = ROOT / "artifacts" / "deploy" / "credentials.env"


def az_binary() -> str:
    found = shutil.which("az") or shutil.which("az.cmd")
    fallback = Path(r"C:\Program Files\Microsoft SDKs\Azure\CLI2\wbin\az.cmd")
    if found:
        return found
    if fallback.exists():
        return str(fallback)
    sys.exit("Azure CLI not found. Install it and run `az login` first.")


AZ = az_binary()


def az(*args: str, quiet: bool = False, cwd: Path = ROOT) -> str:
    done = subprocess.run([AZ, *args], capture_output=True, text=True, cwd=cwd)  # noqa: S603 - fixed binary
    if done.returncode != 0:
        # Never echo the arguments: some carry secrets.
        sys.exit(f"az {args[0]} {args[1] if len(args) > 1 else ''} failed:\n{done.stderr.strip()[-2000:]}")
    if not quiet and done.stderr.strip():
        pass
    return done.stdout.strip()


def run(cmd: list[str]) -> None:
    done = subprocess.run(cmd, capture_output=True, text=True)  # noqa: S603 - fixed argv
    if done.returncode != 0:
        sys.exit(f"{' '.join(cmd[:3])} failed:\n{(done.stdout + done.stderr).strip()[-3000:]}")


def load_or_create_credentials() -> dict[str, str]:
    """Existing values are kept, so a re-deploy does not lock anyone out or change pseudonyms."""
    values: dict[str, str] = {}
    if CREDENTIALS.exists():
        for line in CREDENTIALS.read_text(encoding="utf-8").splitlines():
            if "=" in line and not line.startswith("#"):
                key, _, value = line.partition("=")
                values[key.strip()] = value.strip()
    alphabet = string.ascii_letters + string.digits
    for key in ("PENUMBRA_ANALYST_PASSWORD", "PENUMBRA_SENIOR_PASSWORD", "PENUMBRA_ADMIN_PASSWORD"):
        values.setdefault(key, "".join(secrets.choice(alphabet) for _ in range(24)))
    values.setdefault("PENUMBRA_JWT_SECRET", secrets.token_urlsafe(48))
    values.setdefault("PENUMBRA_PII_HMAC_KEY", secrets.token_urlsafe(48))
    CREDENTIALS.parent.mkdir(parents=True, exist_ok=True)
    CREDENTIALS.write_text(
        "# Penumbra Azure deployment. Generated by scripts/deploy_azure.py. Keep private; not in git.\n"
        "# Log in as analyst / senior / admin with the matching password.\n"
        + "".join(f"{k}={v}\n" for k, v in values.items()),
        encoding="utf-8",
    )
    return values


def stage_context() -> Path:
    """A clean build context: the files git tracks or would track, plus the generated reports.

    `az acr build` reads the whole directory before applying .dockerignore, so building from the
    working tree failed on a lock file a running `next dev` holds open, and would otherwise upload
    whatever happens to be lying around. Building from a staged copy makes the image depend only on
    the repository and the reports.
    """
    import tempfile

    listed = subprocess.run(  # noqa: S603 - fixed argv
        ["git", "ls-files", "-co", "--exclude-standard"], capture_output=True, text=True, cwd=ROOT, check=True
    ).stdout.splitlines()
    stage = Path(tempfile.mkdtemp(prefix="penumbra-build-"))
    extra = [p.relative_to(ROOT).as_posix() for p in (ROOT / "artifacts" / "reports").glob("*.json")]
    for rel in [*listed, *extra]:
        src = ROOT / rel
        if src.is_file():
            dst = stage / rel
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dst)
    # The copilot's ATT&CK corpus (built by `penumbra copilot build`; lives under the data root, not
    # in git). Without it every triage note reads "corpus not built". The directory is created even
    # when the corpus is missing, so the image still builds.
    from penumbra.config import settings
    from penumbra.rag.corpus import CORPUS_FILENAME

    corpus_dir = stage / "deploy" / "data" / "interim"
    corpus_dir.mkdir(parents=True, exist_ok=True)
    corpus = settings().interim_dir / CORPUS_FILENAME
    if corpus.exists():
        shutil.copy2(corpus, corpus_dir / CORPUS_FILENAME)
    else:
        print("  no ATT&CK corpus found; triage notes will say so (penumbra copilot build)")
    stage_models(stage)
    return stage


def stage_models(stage: Path) -> None:
    """The registry champions and the held-out sample pools, for live scoring (ADR-0006).

    Each champion is copied out of the registry only after its manifest verifies: the hashes of
    the bytes being shipped are the hashes the gate report was recorded against. A champion that
    fails verification is not shipped, and the deploy stops.
    """
    from penumbra.config import settings
    from penumbra.models.registry import ModelRegistry

    models_dir = stage / "deploy" / "models"
    samples_dir = stage / "deploy" / "samples"
    models_dir.mkdir(parents=True, exist_ok=True)
    samples_dir.mkdir(parents=True, exist_ok=True)
    for dataset in ("unsw", "nslkdd", "cicids"):
        reg = ModelRegistry(settings().artifact_root / "registry", dataset)
        version = reg.champion()
        if version is None:
            print(f"  {dataset}: no champion; not shipped")
            continue
        problems = reg.verify(version)
        if problems:
            sys.exit(f"{dataset} champion {version} failed verification, not shipping it: {problems}")
        dest = models_dir / dataset
        dest.mkdir(parents=True, exist_ok=True)
        for name in ("detector.joblib", "metadata.json"):
            shutil.copy2(reg.path(version) / name, dest / name)
        pool = settings().artifact_root / "samples" / f"{dataset}_test_sample.csv.gz"
        if pool.exists():
            shutil.copy2(pool, samples_dir / pool.name)
        size = (dest / "detector.joblib").stat().st_size / 2**20
        print(f"  {dataset}: champion {version} verified, {size:.0f} MB{'' if pool.exists() else ' (no sample pool)'}")


SECRET_NAMES = {
    "PENUMBRA_ANALYST_PASSWORD": "pw-analyst",
    "PENUMBRA_SENIOR_PASSWORD": "pw-senior",
    "PENUMBRA_ADMIN_PASSWORD": "pw-admin",
    "PENUMBRA_JWT_SECRET": "jwt-secret",
    "PENUMBRA_PII_HMAC_KEY": "pii-key",
}


def main(rg: str, location: str, base_image: str | None = None, reuse_tag: str | None = None) -> None:
    sys.stdout.reconfigure(line_buffering=True)  # progress shows up when redirected to a log
    account = json.loads(az("account", "show"))
    sub = account["id"]
    print(f"subscription {account['name']}")
    # Install only when missing: `--upgrade` checks the extension index on every run and was seen to
    # hang for 20 minutes on a flaky connection.
    if "containerapp" not in az("extension", "list", "--query", "[].name", "-o", "tsv").split():
        az("extension", "add", "--name", "containerapp", "--only-show-errors")
    for provider in ("Microsoft.App", "Microsoft.ContainerRegistry"):
        az("provider", "register", "--wait", "-n", provider)
    az("group", "create", "-n", rg, "-l", location, "-o", "none")

    registry = "penumbra" + sub.replace("-", "")[:8]
    if not az("acr", "list", "-g", rg, "--query", f"[?name=='{registry}'].name", "-o", "tsv"):
        az("acr", "create", "-g", rg, "-n", registry, "--sku", "Basic", "-l", location, "-o", "none")
    login_server = f"{registry}.azurecr.io"
    tag = reuse_tag or datetime.now(UTC).strftime("%Y%m%d%H%M%S")
    print(f"registry {login_server}; " + (f"reusing images tagged {tag}" if reuse_tag else f"new tag {tag}"))

    # Admin credentials, fetched here and handed straight to Azure - never printed or stored. A
    # managed identity would be nicer, but the "express" Container Apps environment an Azure for
    # Students subscription gets refuses registry identities (ExpressEnvironmentFeatureNotSupported).
    az("acr", "update", "-n", registry, "--admin-enabled", "true", "-o", "none")
    acr = json.loads(az("acr", "credential", "show", "-n", registry))
    registry_args = [
        "--registry-server", login_server,
        "--registry-username", acr["username"],
        "--registry-password", acr["passwords"][0]["value"],
    ]  # fmt: skip

    env_name = "penumbra-env"
    if not az("containerapp", "env", "list", "-g", rg, "--query", f"[?name=='{env_name}'].name", "-o", "tsv"):
        az("containerapp", "env", "create", "-g", rg, "-n", env_name, "-l", location,
           "--logs-destination", "none", "-o", "none")  # fmt: skip
    print(f"environment {env_name}")

    # The API first: the console image has to be built knowing where the API is (Next.js fixes the
    # /api rewrite at build time), and in an express environment the only address that works is the
    # API's own ingress FQDN - app-name addressing (http://penumbra-api) does not resolve there.
    stage = stage_context() if not reuse_tag else None
    if stage is not None:
        az("acr", "login", "-n", registry, "-o", "none")
        base = f"{login_server}/penumbra-api-base:{tag}"
        if base_image:
            # Reuse a local API image whose dependencies are current; the deploy layer copies src/ over it.
            run(["docker", "tag", base_image, base])
            print(f"  reusing {base_image} as the API base")
        else:
            build_and_push(stage, base, "Dockerfile", ".", [])
        build_and_push(
            stage, f"{login_server}/penumbra-api:{tag}", "deploy/api.Dockerfile", ".", [f"BASE={base}"]
        )
    api_fqdn = deploy_api(rg, env_name, f"{login_server}/penumbra-api:{tag}", registry_args)

    if stage is not None:
        build_and_push(
            stage,
            f"{login_server}/penumbra-console:{tag}",
            "console/Dockerfile",
            "console",
            [f"PENUMBRA_API_URL=https://{api_fqdn}", "NEXT_PUBLIC_PENUMBRA_PUBLIC=1"],
        )
        shutil.rmtree(stage, ignore_errors=True)
    fqdn = deploy_console(rg, env_name, f"{login_server}/penumbra-console:{tag}", registry_args)
    print(f"\nhttps://{fqdn}")
    print(f"Logins are in {CREDENTIALS.relative_to(ROOT)} (not printed). Guest access needs none.")


def build_and_push(stage: Path, image: str, dockerfile: str, context: str, args: list[str]) -> None:
    """Built locally and pushed. ACR Tasks (`az acr build`) would need no local Docker, but Azure for
    Students refuses it outright (TasksOperationsNotAllowed)."""
    cmd = ["docker", "build", "-t", image, "-f", str(stage / dockerfile)]
    for arg in args:
        cmd += ["--build-arg", arg]
    run([*cmd, str(stage / context)])
    # Retried: the Python environment is one ~2.5 GB layer, and a dropped connection partway through
    # it was seen in practice. Layers already pushed are skipped on the retry.
    for attempt in range(1, 5):
        done = subprocess.run(["docker", "push", image], capture_output=True, text=True)  # noqa: S603
        if done.returncode == 0:
            break
        print(f"  push attempt {attempt} failed; retrying")
    else:
        sys.exit(f"docker push {image} failed:\n{done.stderr.strip()[-2000:]}")
    print(f"  built and pushed {image.split('/')[-1]}")


def _exists(rg: str, name: str) -> bool:
    return bool(az("containerapp", "list", "-g", rg, "--query", f"[?name=='{name}'].name", "-o", "tsv"))


def deploy_api(rg: str, env_name: str, image: str, registry_args: list[str]) -> str:
    creds = load_or_create_credentials()
    secret_args = [f"{SECRET_NAMES[k]}={v}" for k, v in creds.items() if k in SECRET_NAMES]
    env_args = [f"{k}=secretref:{SECRET_NAMES[k]}" for k in SECRET_NAMES] + [
        "PENUMBRA_GUEST_ACCESS=1",
        "PENUMBRA_SIEM=mock",
        "PENUMBRA_STATE_ROOT=/app/state",
    ]
    if not _exists(rg, "penumbra-api"):
        # Ingress "internal" is requested, and a standard environment honours it. An express
        # environment does not: the API is then reachable at its FQDN from the internet. That is
        # acceptable only because every route except /health, /metrics and the two login routes
        # requires a token and there are no known passwords - see docs/DEPLOYMENT.md.
        az("containerapp", "create", "-g", rg, "-n", "penumbra-api", "--environment", env_name,
           "--image", image, *registry_args, "--ingress", "internal", "--target-port", "8000",
           # One replica: the demo store is SQLite on the container's disk. Two replicas would be two
           # different stores behind one name.
           "--min-replicas", "1", "--max-replicas", "1", "--cpu", "2.0", "--memory", "4Gi",
           "--secrets", *secret_args, "--env-vars", *env_args, "-o", "none")  # fmt: skip
    else:
        az(
            "containerapp",
            "secret",
            "set",
            "-g",
            rg,
            "-n",
            "penumbra-api",
            "--secrets",
            *secret_args,
            "-o",
            "none",
        )
        # Resources on update too: live scoring (ADR-0006) holds the champions in memory, ~0.9 GB.
        az("containerapp", "update", "-g", rg, "-n", "penumbra-api", "--image", image,
           "--cpu", "2.0", "--memory", "4Gi", "--set-env-vars", *env_args, "-o", "none")  # fmt: skip
    fqdn = az("containerapp", "show", "-g", rg, "-n", "penumbra-api",
              "--query", "properties.configuration.ingress.fqdn", "-o", "tsv")  # fmt: skip
    print(f"app penumbra-api ({fqdn})")
    return fqdn


def deploy_console(rg: str, env_name: str, image: str, registry_args: list[str]) -> str:
    if not _exists(rg, "penumbra-console"):
        az("containerapp", "create", "-g", rg, "-n", "penumbra-console", "--environment", env_name,
           "--image", image, *registry_args, "--ingress", "external", "--target-port", "3000",
           "--min-replicas", "1", "--max-replicas", "2", "--cpu", "0.5", "--memory", "1Gi", "-o", "none")  # fmt: skip
    else:
        az("containerapp", "update", "-g", rg, "-n", "penumbra-console", "--image", image, "-o", "none")
    fqdn = az("containerapp", "show", "-g", rg, "-n", "penumbra-console",
              "--query", "properties.configuration.ingress.fqdn", "-o", "tsv")  # fmt: skip
    print("app penumbra-console (public)")
    return fqdn


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--resource-group", default="penumbra-rg")
    parser.add_argument("--location", default="centralindia")
    parser.add_argument(
        "--base-image",
        help="Local API image to build on instead of rebuilding dependencies (e.g. penumbra-api:local).",
    )
    parser.add_argument("--tag", help="Skip building; deploy images already pushed under this tag.")
    a = parser.parse_args()
    main(a.resource_group, a.location, a.base_image, a.tag)
